class FirstTime {
  const FirstTime(this.name);
  final String name;
}

class SecondTime {
  const SecondTime(this.name);
  final String name;
}

var time = <FirstTime>[
  const FirstTime('1'),
  const FirstTime('2'),
  const FirstTime('3'),
  const FirstTime('4'),
  const FirstTime('5'),
  const FirstTime('6'),
  const FirstTime('7'),
  const FirstTime('8'),
  const FirstTime('9'),
  const FirstTime('10'),
  const FirstTime('11'),
  const FirstTime('12'),
];

var time2 = <SecondTime>[
   const SecondTime('00'),
  const SecondTime('01'),
  const SecondTime('02'),
  const SecondTime('03'),
  const SecondTime('04'),
  const SecondTime('05'),
  const SecondTime('06'),
  const SecondTime('07'),
  const SecondTime('08'),
  const SecondTime('09'),
  const SecondTime('10'),
  const SecondTime('11'),
  const SecondTime('12'),
  const SecondTime('13'),
  const SecondTime('14'),
  const SecondTime('15'),
  const SecondTime('16'),
  const SecondTime('17'),
  const SecondTime('18'),
  const SecondTime('19'),
  const SecondTime('20'),
  const SecondTime('21'),
  const SecondTime('22'),
  const SecondTime('23'),
  const SecondTime('24'),
  const SecondTime('25'),
  const SecondTime('26'),
  const SecondTime('27'),
  const SecondTime('28'),
  const SecondTime('29'),
  const SecondTime('30'),
  const SecondTime('31'),
  const SecondTime('32'),
  const SecondTime('33'),
  const SecondTime('34'),
  const SecondTime('35'),
  const SecondTime('36'),
  const SecondTime('37'),
  const SecondTime('38'),
  const SecondTime('39'),
  const SecondTime('40'),
  const SecondTime('41'),
  const SecondTime('42'),
  const SecondTime('43'),
  const SecondTime('44'),
  const SecondTime('45'),
  const SecondTime('46'),
  const SecondTime('47'),
  const SecondTime('48'),
  const SecondTime('49'),
  const SecondTime('50'),
  const SecondTime('51'),
  const SecondTime('52'),
  const SecondTime('53'),
  const SecondTime('55'),
  const SecondTime('56'),
  const SecondTime('57'),
  const SecondTime('58'),
  const SecondTime('59'),
  
];
